### ISSUE TITLE
Slayers: roadmap

### ISSUE THREAD

**Issue by jcp19** [viperproject/VerifiedSCION#103]
- [x] Merge with upstream (PR #100)

After addressing PR https://github.com/viperproject/gobra/issues/555:
- [x] Make global variables immutable wherever possible (pending #106)
- [x] Update PR #89 and merge 
- [x] Mark methods as `@ignore` in PR https://github.com/viperproject/VerifiedSCION/pull/69 and merge it to allow concurrent work on the dataplane
- [ ] Clean-up debt to enable performance improvements:
    - [x] Issue #97 (fixed in #145)
    - [x] Issue #98 
    - [ ] Issue #101 
    - [x] ~~Silicon PR https://github.com/viperproject/silicon/pull/651~~
- [x] (*SCION).DecodeFromBytes
- [x] (*SCION).SerializeTo
- [x]  (*SCION).LayerType
- [x]  (*SCION).CanDecode
- [x]  (*SCION).NextLayerType
- [x]  (*SCION).LayerPayload
- [ ] **(Urgent) Verify the extension headers in extn.go, implement subtyping relation with gopacket stuff**

To be verified on a per-need basis:
- [x]  (*SCION).SetDstAddr (done by @Dspil)
- [x]  (*SCION).SetSrcAddr (done by @Dspil)
- [x]  (*SCION).DstAddr (done by @Dspil)
- [x]  (*SCION).SrcAddr (done by @Dspil)
- [ ] scion.go: `decodeSCION` (tricky, may require changes to `SCION`)

Important:
- [x] **Check what are the intended supertypes of SCION** (URGENT)
    - [x] gopacket.Layer
    - [x] gopacket.NetworkLayer
    - [x] gopacket.SerializableLayer

**Comment by jcp19** [comment]
All open tasks here have a corresponding issue in the issue tracker. I will close this issue to keep this list from getting even larger
