### ISSUE TITLE
packScmp: roadmap

### ISSUE THREAD

**Issue by Dspil** [viperproject/VerifiedSCION#104]
- [ ] Verify dataplane.go/packScmp
  - [ ]  Verify dataplane.go/prepareScmp
    - [x] Verify scmp.go to get full access to SCMP struct
      - [x] Verify scion.go/computeChecksum
        - [x] Verify scion.go/pseudoHeaderChecksum
        - [x]  Verify scion.go/upperLayerChecksum 
    - [ ] Verify scion.go/SetDstAddr and scion.go/SetSrcAddr
      - [ ] Verify scion.go/packAddr

**Comment by Dspil** [comment]
I moved the roadmap to the corresponding pull request:  https://github.com/viperproject/VerifiedSCION/pull/126
